// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXWhPFN32uCKilCf7ay2ZQsPA63y_bcdA',
    appId: '1:137433603546:web:917c727aff46cb341874e3',
    messagingSenderId: '137433603546',
    projectId: 'flutter-quiz-firebase-b5482',
    authDomain: 'flutter-quiz-firebase-b5482.firebaseapp.com',
    storageBucket: 'flutter-quiz-firebase-b5482.firebasestorage.app',
    measurementId: 'G-XHX7GNXPV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2TVjSbTJgBv8x-ZDGZcdRi5cuwfZXQs',
    appId: '1:137433603546:android:5dc19a54081712801874e3',
    messagingSenderId: '137433603546',
    projectId: 'flutter-quiz-firebase-b5482',
    storageBucket: 'flutter-quiz-firebase-b5482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFz1kGtq1rLJS7yhjX3No-pIXEMFVAv5w',
    appId: '1:137433603546:ios:59c019beb0b05d481874e3',
    messagingSenderId: '137433603546',
    projectId: 'flutter-quiz-firebase-b5482',
    storageBucket: 'flutter-quiz-firebase-b5482.firebasestorage.app',
    iosBundleId: 'com.example.quizCultureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFz1kGtq1rLJS7yhjX3No-pIXEMFVAv5w',
    appId: '1:137433603546:ios:59c019beb0b05d481874e3',
    messagingSenderId: '137433603546',
    projectId: 'flutter-quiz-firebase-b5482',
    storageBucket: 'flutter-quiz-firebase-b5482.firebasestorage.app',
    iosBundleId: 'com.example.quizCultureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXWhPFN32uCKilCf7ay2ZQsPA63y_bcdA',
    appId: '1:137433603546:web:8a3a2d2d1bf3f8611874e3',
    messagingSenderId: '137433603546',
    projectId: 'flutter-quiz-firebase-b5482',
    authDomain: 'flutter-quiz-firebase-b5482.firebaseapp.com',
    storageBucket: 'flutter-quiz-firebase-b5482.firebasestorage.app',
    measurementId: 'G-1R86M1EZW1',
  );
}
